version: '3'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: webserver-php73
    restart: always
    expose:
      - '9000'
    ports:
      - '80:80'
      - '2222:22'
      - '443:443'
    links:
      - redis
      - mysql
    volumes:
      - '${DOCUMENT_ROOT-./www}:/var/www/html'
      - '${PHP_INI-./config/php/php.ini}:/etc/php-7.3.d/custom.ini'
      - '${VHOSTS_DIR-./config/apache/vhosts}:/etc/httpd/conf.sites'
      - '${LOG_DIR-./logs/apache2}:/var/log/httpd/'
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal
  redis:
    image: redis:latest
    container_name: redis-php73
    restart: always
    ports:
      - '6379:6379'
  mysql:
    build: ./bin/mysql
    container_name: mysql-php73
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root